[workspace]
resolver = "3"
members = ["bellycoin", "crypto", "runtime", "wallet", "common"]
exclude = [
    "dependency",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/mandala-17/bellycoin"
authors = ["Mandala <https://x.com/mandala17th>"]

[profile.bench]
debug = true

[workspace.dependencies]
argon2 = { version = "0.5.3", default-features = false, features = ["alloc"], path = "dependency/argon2/argon2" }
bip39 = "2.2"
borsh = { version = "1.5", features = ["derive"], path = "dependency/traits/borsh" }
fn-dsa = { version = "0.4.0", default-features = false, path = "dependency/fn-dsa/fn-dsa" }
getrandom = { version = "0.4.3", default-features = false }
hex = "0.4"
igd-next = "0.16"
rand_core_06 = { package = "rand_core", version = "0.6.4", features = ["getrandom"] }
redb = "4.2.0"
serde = { version = "1", features = ["derive"], path = "dependency/traits/serde" }
serde_json = "1"
sha3 = { version = "0.12.0", default-features = false, path = "dependency/sha3/sha3" }
static_assertions = { version = "1.1.0", path = "dependency/utils/static_assertions" }
zeroize = { version = "1.9.0", features = ["alloc", "derive"], path = "dependency/traits/zeroize" }

crypto = { path = "crypto", default-features = false }
bellycoin = { path = "bellycoin", default-features = false }
common = { path = "common" }

[patch.crates-io]
serde = { path = "dependency/traits/serde" }
serde_core = { path = "dependency/traits/serde_core" }
serde_derive = { path = "dependency/traits/serde_derive" }

autocfg = { path = "dependency/utils/autocfg" }
block-buffer = { path = "dependency/utils/block-buffer" }
crypto-common = { path = "dependency/utils/crypto-common-0.1.7" }
digest = { path = "dependency/traits/digest-0.10.7" }
generic-array = { path = "dependency/utils/generic-array" }
hybrid-array = { path = "dependency/utils/hybrid-array" }

num-traits = { path = "dependency/traits/num-traits" }

proc-macro2 = { path = "dependency/proc-macro/proc-macro2" }
quote = { path = "dependency/proc-macro/quote" }
syn = { path = "dependency/proc-macro/syn-2.0.119" }
unicode-ident = { path = "dependency/proc-macro/unicode-ident" }

rand_core = { path = "dependency/traits/rand_core" }
signature = { path = "dependency/traits/signature" }

cpubits = { path = "dependency/utils/cpubits" }
ctutils = { path = "dependency/utils/ctutils" }
subtle = { path = "dependency/utils/subtle" }
typenum = { path = "dependency/utils/typenum" }
version_check = { path = "dependency/utils/version_check" }

zeroize_derive = { path = "dependency/traits/zeroize_derive" }