[package]
name = "node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "bellycoin"
path = "src/main.rs"

[features]
default = ["mainnet"]
mainnet = ["bellycoin/mainnet", "wallet/mainnet"]

[dependencies]
borsh.workspace = true
hex.workspace = true
serde_json.workspace = true
serde.workspace = true
igd-next.workspace = true
getrandom.workspace = true
redb.workspace = true
bellycoin.workspace = true
wallet = { path = "../wallet", default-features = false }